# Exercício:

## 01 – Obtenha os resultados e retorne o objeto e código em Python dos seguintes cálculos:
a) 2.0 + 3.0 / 5.0

b) (a + 10.2) - 5.0 * 2.0

c) a / b + 33.8

d) a / (b + c)

e) d * 2

In [1]:
a = 2.0 + 3.0 / 5.0
b = (a + 10.2) - 5.0 * 2.0
c = a / b + 33.8
d = a / (b + c)
e = d * 2

print('O resultado de A é ', a)
print('O resultado de B é ', b)
print('O resultado de C é ', c)
print('O resultado de D é ', d)
print('O resultado de E é ', e)

O resultado de A é  2.6
O resultado de B é  2.799999999999999
O resultado de C é  34.72857142857143
O resultado de D é  0.0692805481537876
O resultado de E é  0.1385610963075752


## 02 – Obtenha os resultados e retorne o código do objeto em Python dos seguintes cálculos:
a) [2.0, 3.0, 5.0] + [10, 20, 30]

b) lista_a * 2

c) lista_a + lista_b

d) lista_a / (lista_b * lista_c)

In [2]:
import numpy as np

lista_a = np.array([2.0, 3.0, 5.0])
lista_b = np.array([10, 20, 30])
lista_c = np.array([1, 2, 3])

a = lista_a + lista_b
b = lista_a * 2
c = lista_a + lista_b
d = lista_a / (lista_b * lista_c)

print(a, b, c, d)

[12. 23. 35.] [ 4.  6. 10.] [12. 23. 35.] [0.2        0.075      0.05555556]


## 03 – Usando os objetos simples obtidos no exercício 01 (a, b, c, d, e), instancie uma  lista. Instancie também uma segunda lista contendo a raiz quadrada dos valores obtidos nos objetos simples. Instancie uma terceira lista, concatenando as duas primeiras. Recupere a última lista.

In [3]:
import math

a = 2.6
b = 2.8
c = 34.72857
d = 0.06927
e = 0.13854

lista1 = [a, b, c, d, e]
lista2 = [math.sqrt(x) for x in lista1]
lista3 = lista1 + lista2

print(lista3)

[2.6, 2.8, 34.72857, 0.06927, 0.13854, 1.61245154965971, 1.6733200530681511, 5.8930951120782025, 0.2631919451655008, 0.3722096183604072]


## 04 – Duplique os valores contidos na lista final obtida no exercício anterior e converta para um array numpy. Remodele (reshape) o array, para que contenha 5 linhas e 4 colunas. Recupere o array.

In [4]:
import numpy as np

lista3 = [2.6, 2.8, 34.72857, 0.06927, 0.13854,
          1.61245, 1.67332, 5.89394, 0.26320, 0.37221]

lista_duplicada = lista3 * 2
array = np.array(lista_duplicada)
array = array.reshape(5, 4)

print(array)

[[ 2.6      2.8     34.72857  0.06927]
 [ 0.13854  1.61245  1.67332  5.89394]
 [ 0.2632   0.37221  2.6      2.8    ]
 [34.72857  0.06927  0.13854  1.61245]
 [ 1.67332  5.89394  0.2632   0.37221]]


## 05 – Do array numpy obtenha uma lista contendo a média dos valores de cada uma das colunas.

In [5]:
medias_colunas = array.mean(axis=0).tolist()

print(medias_colunas)

[7.880725999999998, 2.149574, 7.880725999999998, 2.1495740000000003]


## 06 – Insira as médias das colunas no final do array do exercício 4.

**Contexto:**
- No exercício 4, você criou um array numpy com 5 linhas e 4 colunas (totalizando 20 valores)
- No exercício 5, você calculou a média de cada uma das 4 colunas (resultando em uma lista com 4 valores)

**Tarefa:**
1. Use o atributo `shape` do array do exercício 4 para calcular o número total de elementos.
2. Insira a lista de médias (do exercício 5) no final de outro array criado
3. Recupere e exiba o array resultante


Obs.:  Atributos não usam () na chamada.

In [6]:
linhas, colunas = array.shape
total_elementos = linhas * colunas

import numpy as np

medias_array = np.array(medias_colunas).reshape(1, colunas)
novo_array = np.vstack((array, medias_array))

print(novo_array)

[[ 2.6       2.8      34.72857   0.06927 ]
 [ 0.13854   1.61245   1.67332   5.89394 ]
 [ 0.2632    0.37221   2.6       2.8     ]
 [34.72857   0.06927   0.13854   1.61245 ]
 [ 1.67332   5.89394   0.2632    0.37221 ]
 [ 7.880726  2.149574  7.880726  2.149574]]


## 07 – Remodele (reshape) o array do exercício anterior, para que contenha 4 colunas. Converta este objeto da classe array para DataFrame. Arredonde todos os valores para até 3 casas decimais. Recupere a DataFrame.

In [7]:
import numpy as np
import pandas as pd

linhas, colunas = novo_array.shape
array_reshape = novo_array.reshape(-1, 4)
df = pd.DataFrame(array_reshape)
df = df.round(3)

print(df)

        0      1       2      3
0   2.600  2.800  34.729  0.069
1   0.139  1.612   1.673  5.894
2   0.263  0.372   2.600  2.800
3  34.729  0.069   0.139  1.612
4   1.673  5.894   0.263  0.372
5   7.881  2.150   7.881  2.150


## 08 – A última instancia desta DataFrame deve conter as médias dos valores contidos por coluna, o que foi determinado nos exercícios anteriores. Instancie um objeto contendo as médias dos valores em cada linha. Insira este objeto como uma nova coluna na DataFrame. Recupere a DataFrame.

In [8]:
medias_linhas = df.mean(axis=1)
df["media_linhas"] = medias_linhas

print(df)

        0      1       2      3  media_linhas
0   2.600  2.800  34.729  0.069      10.04950
1   0.139  1.612   1.673  5.894       2.32950
2   0.263  0.372   2.600  2.800       1.50875
3  34.729  0.069   0.139  1.612       9.13725
4   1.673  5.894   0.263  0.372       2.05050
5   7.881  2.150   7.881  2.150       5.01550


## 09 – Usando o método dos objetos de classe DataFrame, describe(), compare os resultados contidos na última linha e última coluna da DataFrame.

Obs.: O método dos objetos de classe DataFrame, transpose(), inverte linhas por colunas.

In [9]:
desc = df.describe()
print(desc)

ultima_linha = df.iloc[-1]
ultima_coluna = df["media_linhas"]

print("Última linha:\n", ultima_linha)
print("\nÚltima coluna:\n", ultima_coluna.describe())

               0         1          2         3  media_linhas
count   6.000000  6.000000   6.000000  6.000000      6.000000
mean    7.880833  2.149500   7.880833  2.149500      5.015167
std    13.455228  2.108142  13.455228  2.108142      3.758539
min     0.139000  0.069000   0.139000  0.069000      1.508750
25%     0.615500  0.682000   0.615500  0.682000      2.120250
50%     2.136500  1.881000   2.136500  1.881000      3.672500
75%     6.560750  2.637500   6.560750  2.637500      8.106813
max    34.729000  5.894000  34.729000  5.894000     10.049500
Última linha:
 0               7.8810
1               2.1500
2               7.8810
3               2.1500
media_linhas    5.0155
Name: 5, dtype: float64

Última coluna:
 count     6.000000
mean      5.015167
std       3.758539
min       1.508750
25%       2.120250
50%       3.672500
75%       8.106813
max      10.049500
Name: media_linhas, dtype: float64


## 10 – Edite o nome das colunas e dos index, para indicar onde estão as médias. Qual a média das médias?

In [ ]:
df.columns = ["col1", "col2", "col3", "col4", "media_linhas"]
df.index = ["linha1", "linha2", "linha3", "linha4", "linha5", "media_colunas"]
media_das_medias = df["media_linhas"].mean()

print(df)
print('A media das medias é:', media_das_medias)

                 col1   col2    col3   col4  media_linhas
linha1          2.600  2.800  34.729  0.069      10.04950
linha2          0.139  1.612   1.673  5.894       2.32950
linha3          0.263  0.372   2.600  2.800       1.50875
linha4         34.729  0.069   0.139  1.612       9.13725
linha5          1.673  5.894   0.263  0.372       2.05050
media_colunas   7.881  2.150   7.881  2.150       5.01550
A media das medias é: 5.0151666666666666
