# Exercício:

## 01 – Obtenha os resultados e retorne o código Python dos seguintes cálculos:

<br>a = 2.0 + 3.0 / 5.0 == 10
<br>b = (a + 10.2) - 5.0 * 2.0 <= 2.9
<br>c = 10 <= a / b + 33.8 < 100
<br>d = 5 != a / (b + c)
<br>e = 33 == d * 2

In [1]:
a = 2.0 + 3.0 / 5.0 == 10
b = (a + 10.2) - 5.0 * 2.0 <= 2.9
c = 10 <= a / b + 33.8 < 100
d = 5 != a / (b + c)
e = 33 == d * 2

print(a, b, c, d, e)

False True True True False


## 02 – Altere os operadores relacionais para modificar o resultado de cada uma das comparações.

<br>('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>['a',1,True,'b',0,False] > ['a',True,1]
<br>['a',1,True,'b',0,False] == 1
<br>['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [2]:
r1 = ('a',1,True,'b',0,False) == ('a',True,1,'b',False,0)
r2 = ['a',1,True,'b',0,False] == ('a',True,1,'b',False,0)
r3 = ['a',1,True,'b',0,False] == ['a',True,1,'b',False,0]
r4 = ['a',1,True,'b',0,False] < ['a',True,1]
r5 = ['a',1,True,'b',0,False] != 1
r6 = ['a',True,1] >= ['a',True,1] > ['a',1,True,'b',0,False]

print(r1, r2, r3, r4, r5, r6)

True False True False True False


## 03 – Usando o método DataFrame.to_csv(‘nome_do_arquivo.csv’) exporte o objeto obtido no exercício 10 da aula anterior para um arquivo CSV. Usando o método pd.read_csv(‘nome_do_arquivo.csv’) instancie uma DataFrame. Use o valor ‘Unnamed: 0’ no parâmetro index_col, para ajustar o index. Arredonde os valores para até três casas decimais, usando o método round().
Recupere a DataFrame.

In [4]:
import pandas as pd

df_novo = pd.read_csv("dataframel7e10.csv", index_col="Unnamed: 0")
df_novo = df_novo.round(3)

print(df_novo)

                 col1   col2    col3   col4  media_linhas
linha1          2.600  2.800  34.729  0.069        10.050
linha2          0.139  1.612   1.673  5.894         2.330
linha3          0.263  0.372   2.600  2.800         1.509
linha4         34.729  0.069   0.139  1.612         9.137
linha5          1.673  5.894   0.263  0.372         2.050
media_colunas   7.881  2.150   7.881  2.150         5.015


## 04 – Instancie um numpy array que apresente o mesmo formato (linhas e colunas) da DataFrame. Este array deve conter apenas inteiros uns.
Recupere o array.

Obs.: Procure na internet o método numpy.ones()

In [5]:
import numpy as np


linhas, colunas = df_novo.shape
array_uns = np.ones((linhas, colunas), dtype=int)

print(array_uns)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## 05 – Quantos dos valores contidos na DataFrame são iguais aos valores no array?

In [6]:
comparacao = (df_novo.values == array_uns)
quantidade_iguais = comparacao.sum()

print(quantidade_iguais)

0


## 06 – Quantos dos valores contidos na DataFrame são superiores aos valores no array?

In [7]:
comparacao = (df_novo.values > array_uns)
quantidade_superiores = comparacao.sum()

print(quantidade_superiores)

22


## 07 – Quantos dos valores contidos na DataFrame são iguais ou inferiores aos valores no array?

In [8]:
quantidade = (df_novo.values <= array_uns).sum()
print(quantidade)

8


## 08 – Quantos dos valores contidos na DataFrame estão entre 0 e 1?

In [9]:
quantidade = ((df_novo.values >= 0) & (df_novo.values <= 1)).sum()
print(quantidade)

8


## 09 – Quantos dos valores das médias das linhas são inferiores ou iguais à 5?

Obs 1.: Usando o método de classe, você pode converter qualquer objeto em outra classe. Ex. obj = list(array)

Obs 2.: Assim com o objeto da classe str, listas também possuem a função count()

In [10]:
quantidade = (df_novo["media_linhas"] <= 5).sum()
print(quantidade)

3


## 10 – Quantos dos valores das médias das colunas são superiores à 5?

In [11]:
quantidade = (df_novo.loc["media_colunas", ["col1","col2","col3","col4"]] > 5).sum()
print(quantidade)

2
